Repository jupyterlab-contrib/jupyter-secrets-manager, pull requests merged in 2025-03, with the labels that each got.

#2 Fix repo URL in `package.json` and some other CI checks
  README.md
  package.json
  ui-tests/tests/jupyter_secrets_manager.spec.ts
  yarn.lock
Labels: maintenance

#1 Add a default connector plugin
  src/connectors/in-memory.ts
  src/connectors/index.ts
  src/index.ts
Labels: enhancement

#3 manager's list method returning ids and secret values
  src/connectors/in-memory.ts
  src/connectors/local-storage.ts
  src/manager.ts
  src/token.ts
Labels: enhancement

#5 Fix the detachAll method
  src/manager.ts
  src/token.ts
Labels: bug

#4 Allow the DataConnector to partially implements IDataConnector
  src/manager.ts
  src/token.ts
Labels: enhancement

#7 Add the namespace argument in public functions accessing the secrets
  src/manager.ts
  src/token.ts
Labels: enhancement
